# Default values for chart-sa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harrylawsmith/sa-frontend
  tag: mini
  # pullPolicy: IfNotPresent
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

